//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoHub {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoHub.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please disconnect your device from PC.
        /// </summary>
        internal static string DisconnectDeviceMessage {
            get {
                return ResourceManager.GetString("DisconnectDeviceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Library Blocked.
        /// </summary>
        internal static string DisconnectDeviceMessageTitle {
            get {
                return ResourceManager.GetString("DisconnectDeviceMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated. Add a tag and upload the image.
        /// </summary>
        internal static string FacebookAddTagText {
            get {
                return ResourceManager.GetString("FacebookAddTagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to retrieve access token....
        /// </summary>
        internal static string FacebookRetrieveAccessTokenText {
            get {
                return ResourceManager.GetString("FacebookRetrieveAccessTokenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on Facebook.
        /// </summary>
        internal static string FacebookShare {
            get {
                return ResourceManager.GetString("FacebookShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully uploaded to Facebook.
        /// </summary>
        internal static string FacebookUploadSuccessMessage {
            get {
                return ResourceManager.GetString("FacebookUploadSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Success.
        /// </summary>
        internal static string FacebookUploadSuccessTitle {
            get {
                return ResourceManager.GetString("FacebookUploadSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on &quot;OK, I&apos;ll Authorize it&quot;..
        /// </summary>
        internal static string FlickrAuthorizeText {
            get {
                return ResourceManager.GetString("FlickrAuthorizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here yet. Your camera roll pictures will be displayed here.
        /// </summary>
        internal static string NothingHereCameraRoll {
            get {
                return ResourceManager.GetString("NothingHereCameraRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here yet. Your sample pictures will be displayed here.
        /// </summary>
        internal static string NothingHereSamplePictures {
            get {
                return ResourceManager.GetString("NothingHereSamplePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here yet. Your saved pictures will be displayed here.
        /// </summary>
        internal static string NothingHereSavedPictures {
            get {
                return ResourceManager.GetString("NothingHereSavedPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find your picture in &quot;Saved Pictures&quot; album.
        /// </summary>
        internal static string PictureSavedMessage {
            get {
                return ResourceManager.GetString("PictureSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture saved.
        /// </summary>
        internal static string PictureSavedMessageTitle {
            get {
                return ResourceManager.GetString("PictureSavedMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Error occurred. Please try again.
        /// </summary>
        internal static string SomeErrorMessage {
            get {
                return ResourceManager.GetString("SomeErrorMessage", resourceCulture);
            }
        }
    }
}
